name: lessico bot prod
run-name: lessico-bot
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v3
       - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
       - run: docker compose build
       - run: docker compose down
       - run: export BOT_TOKEN = ${{ secrets.BOT_TOKEN }}
       - run: docker compose up -d
       - run: docker image prune -f