name: lessico bot prod
run-name: lessico-bot
on: push
jobs:
  deploy:
    - steps:
       - name: Check out repository code
       uses: actions/checkout@v3
       - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
       - run: docker compose build
       - run: docker compose down
       - run: docker compose up -d
       - run: docker image prune -f